config/routes.rb
Channelback::Application.routes.draw do

get '/users/sign_in' => 'users#sign_in',:as => :sign_in
get '/admin/sign_in' => 'admins#sign_in',:as => :admin_sign_in
get '/admin' => 'admins#sign_in'
get '/admin/users' => 'users#index',:as => :admin_users
get '/admin/activity' => 'admins#activity',:as => :activity
post '/users/sign_in' => 'users#login',:as => :login
post '/admin/sign_in' => 'admins#login',:as => :admin_login
post '/users/logout' => 'users#logout',:as => :logout
post '/admin/logout' => 'admins#logout',:as => :admin_logout
post '/comment_votes/:id' => 'comment_votes#destroy'
post '/posts/search' => 'posts#search',:as => :search
post '/admin/users/:id' => 'users#promote'
delete '/admin/users/:id' => 'users#demote'
root :to => 'posts#index'
resources :users
resources :posts
resources :admins
resources :categories
resources :comments
resources :post_votes
resources :comment_votes

end

app/views/admins/_dashboard_links.haml
%li.navbar-link= link_to 'Manage Users',admin_users_path
%li.navbar-link= link_to 'Manage Admins',admins_path
%li.navbar-link= link_to 'Manage Posts',posts_path
%li.navbar-link= link_to 'Manage Categories',categories_path
%li.navbar-link= link_to 'Activity Report',activity_path
%li.navbar-link= link_to 'Sign Out', admin_logout_path,:method => :post

app/views/admins/_form.html.haml
= form_for(@admin) do |f|
  .field
    = f.label :email
    = f.text_field :email
    %br/
  .field
    = f.label :name
    = f.text_field :name
    %br/
  .field
    = f.label :password
    = f.password_field :password
    %br/
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
    %br/
  .actions
    = f.submit

app/views/admins/activity.html.haml
%h2.page-header Popular Posts
- @posts.each do |post|
  %h4= link_to post.title, post_path(post)
  %p= 'Votes Received = '+ post.post_votes.count.to_s
  %br
%br

%h2.page-header Popular Comments
- @comments.each do |comment|
  %h4= link_to comment.text,post_path(comment.post)
  %p= 'Votes Received = '+ comment.comment_votes.count.to_s

app/views/admins/index.html.haml
%h1 Admins
- @admins.each do |admin|
  %p= admin.name
  - if @current_admin and @current_admin.id.eql? admin.id
    %p= link_to 'Delete',{:id => admin.id,:action => :destroy},:method => :delete

app/views/admins/new.html.haml
= render 'admins/form'

app/views/admins/sign_in.html.haml
= form_tag admin_login_path,:method => :post do
   = label_tag "Email"
   = text_field_tag "email"
   %br/
   = label_tag "Password"
   = password_field_tag "password"
   %br/
   = submit_tag "Log In"