config/routes.rb
Channelback::Application.routes.draw do

get '/users/sign_in' => 'users#sign_in',:as => :sign_in
get '/admin/sign_in' => 'admins#sign_in',:as => :admin_sign_in
get '/admin' => 'admins#sign_in'
get '/admin/users' => 'users#index',:as => :admin_users
get '/admin/activity' => 'admins#activity',:as => :activity
post '/users/sign_in' => 'users#login',:as => :login
post '/admin/sign_in' => 'admins#login',:as => :admin_login
post '/users/logout' => 'users#logout',:as => :logout
post '/admin/logout' => 'admins#logout',:as => :admin_logout
post '/comment_votes/:id' => 'comment_votes#destroy'
post '/posts/search' => 'posts#search',:as => :search
post '/admin/users/:id' => 'users#promote'
delete '/admin/users/:id' => 'users#demote'
root :to => 'posts#index'
resources :users
resources :posts
resources :admins
resources :categories
resources :comments
resources :post_votes
resources :comment_votes

end

app/models/user.rb
class User < ActiveRecord::Base
  # To change this template use File | Settings | File Templates.
  attr_accessible :name,:email,:handle,:password,:password_confirmation

  validates :email, :uniqueness => :true
  validates :email,:presence => true
  validate :check_password_confirmation
  validates :email,format: {with: /[a-zA-z\._]*@[a-zA-z\._]*\.com/}

  has_many :posts

  def self.authenticate(email,password)
    @user = User.find_by_email(email)
    if not @user.nil? and @user.password.eql? password
      return @user
    else
      nil
    end
  end

  def check_password_confirmation
    errors.add(:password,'Password doesn\'t match password confirmation') if not password.eql? password_confirmation
  end

  def is_admin?
    not Admin.find_by_email(email).nil?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    if @current_admin.nil?
      redirect_to admin_sign_in_path
    else
      @users = User.all
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice]= 'You may now login'
      redirect_to sign_in_path
    else
      redirect_to new_user_path
    end
  end

  def sign_in
    if not session[:user_id].nil?
      redirect_to posts_path
    end
  end

  def login
    @user = User.authenticate(params[:email],params[:password])
    if @user.nil?
      flash[:error] = 'Invalid username or password'
      redirect_to sign_in_path
    else
      session[:user_id] = @user.id
      flash[:notice]= 'Welcome and Bien Venue'
      redirect_to posts_path
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice]= 'You have been logged out'
    redirect_to sign_in_path
  end

  def promote
    @user = User.find(params[:id]).serializable_hash.to_hash
    @admin = Admin.new(@user.except('id').except('handle').except('comments_id'))
    @admin.save
    redirect_to admin_users_path
  end

  def demote
   @admin = Admin.find_by_email(User.find(params[:id]).email)
   puts 'demote' + @admin.serializable_hash.to_hash.to_s
   @admin.destroy
   if session[:admin_id].eql? @admin.id
     session[:admin_id] = nil
   end
   redirect_to admin_users_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

end

app/views/users/_form.html.haml
= form_for(@user) do |f|
  .field
    = f.label :email
    = f.text_field :email
    %br/
  .field
    = f.label :name
    = f.text_field :name
    %br/
  .field
    = f.label :password
    = f.password_field :password
    %br/
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
    %br/
  .actions
    = f.submit 'Sign Up!'

app/views/users/_user_links.html.haml
%li.navbar-link= link_to 'All Posts',posts_path
%li.navbar-link= link_to 'New Post',new_post_path
%li.navbar-link= link_to 'Sign Out', logout_path,:method => :post

app/views/users/index.html.haml
%h1.page-header Users
- @users.each do |user|
  %h3.label= 'Name'
  %p.info= user.name
  %h3.label= 'Email'
  %p.info= user.email
  - if not @current_admin.nil?
    -if user.is_admin?
      %p= button_to 'Demote',{:controller => :users,:action => :demote,:id => user.id},:method => :delete
    -else
      %p= button_to 'Promote',:controller => :users,:action => :promote,:method => :post,:id => user.id
  %p= button_to 'Delete',{:controller => :users,:action => :destroy,:id => user.id},:method => :delete

app/views/users/new.html.haml
%h2.page-header= 'Sign Up Form'
= render 'users/form'

app/views/users/sign_in.html.haml
= form_tag login_path,:method => :post do
   = label_tag "Email"
   = text_field_tag "email"
   %br/
   = label_tag "Password"
   = password_field_tag "password"
   %br/
   = submit_tag "Log In"
= link_to 'First Time Here?',new_user_path