config/routes.rb
Channelback::Application.routes.draw do

get '/users/sign_in' => 'users#sign_in',:as => :sign_in
get '/admin/sign_in' => 'admins#sign_in',:as => :admin_sign_in
get '/admin' => 'admins#sign_in'
get '/admin/users' => 'users#index',:as => :admin_users
get '/admin/activity' => 'admins#activity',:as => :activity
post '/users/sign_in' => 'users#login',:as => :login
post '/admin/sign_in' => 'admins#login',:as => :admin_login
post '/users/logout' => 'users#logout',:as => :logout
post '/admin/logout' => 'admins#logout',:as => :admin_logout
post '/comment_votes/:id' => 'comment_votes#destroy'
post '/posts/search' => 'posts#search',:as => :search
post '/admin/users/:id' => 'users#promote'
delete '/admin/users/:id' => 'users#demote'
root :to => 'posts#index'
resources :users
resources :posts
resources :admins
resources :categories
resources :comments
resources :post_votes
resources :comment_votes

end

app/models/post.rb
class Post < ActiveRecord::Base
  # To change this template use File | Settings | File Templates.
  attr_accessible :title,:content
  belongs_to :user
  belongs_to :category
  has_many :tags
  has_many :comments
  has_many :post_votes
  accepts_nested_attributes_for :tags
  validates :title,:presence => true
  validates :category,:presence => true
  validates :user,:presence => true

  def tag_string
    return tags.collect{|t| t.name}.join(',')
  end

  def active_score
    post_votes_count = post_votes.count
    comment_votes_count = comments.map {|v| v.comment_votes.count }.inject(0) {|p,v| p + v}
    first_post_time = Post.all.sort {|p,q| p.created_at <=> q.created_at}.first.created_at
    -(post_votes_count + 0.5 * comment_votes_count + 0.1*(created_at - first_post_time)/36e6)
  end

  def printed_user_name
    if user.nil?
      'Anonymous'
    else
      user.name
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # To change this template use File | Settings | File Templates.

  def index
    @posts = Post.all.sort {|p,q| p.active_score <=> q.active_score}
    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
    if not @current_user.nil?
      @vote = PostVote.find_vote(@post.id,@current_user.id).first
    end
  end

  def new
    if @current_user.nil?
      redirect_to sign_in_path
    else
      @categories = Category.all
      @post = Post.new
    end
  end

  def edit
    if @current_user.nil?
      redirect_to sign_in_path
    else
      @post = Post.find(params[:id])
      @categories = Category.all
    end

  end

  def update
    if @current_user.nil?
      redirect_to sign_in_path
    else
      @post = Post.find(params[:id])
      @post.category = Category.find(params[:post][:category_id])
      tags = params[:post][:tags]
      @post.tags = []
      tags.split(',').each do |tag|
        t = Tag.find_by_name(tag)
        if t.nil?
          t = Tag.new(:name => tag)
          t.save
        end
        t.post= @post
        @post.tags << t
      end
      @post.assign_attributes(params[:post].except(:category_id).except(:tags))
      if @post.save
        redirect_to posts_path
      else
        redirect_to edit_post_path
      end
    end
  end

  def create
    if @current_user.nil?
      redirect_to sign_in_path
    else
      @post = Post.new(params[:post].except(:category_id).except(:tags))
      @post.user = @current_user
      @post.category= Category.find(params[:post][:category_id])
      tags = params[:post][:tags]
      tags.split(',').each do |tag|
        t = Tag.find_by_name(tag)
        if t.nil?
          t = Tag.new(:name => tag)
          t.save
        end
        t.post = @post
        @post.tags << t
      end
      if @post.save
        redirect_to posts_path
      else
        redirect_to new_post_path
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def search
    @categories = Category.all
    @posts = Post.find_all_by_category_id(params[:category][:category_id]).select {|p| p.title.downcase.include? params[:query].downcase or p.tag_string.downcase.include? params[:query].downcase or p.content.downcase.include? params[:query].downcase or p.user.name.downcase.include? params[:query].downcase}
    render 'index'
  end

end

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  .field
    = f.label :title
    = f.text_field :title
    %br/
  .field
    = f.label :content
    = f.text_area :content
    %br/
  .field
    = f.label :category
    = f.select :category_id, @categories.map {|c| [c.name,c.id]}
    %br/
  .field
    = f.label :tags
    = f.text_field :tags,:value => @post.tag_string
    %br/
  .actions
    = f.submit

app/views/posts/edit.html.haml
%h1= 'Editing '+ @post.title+' by ' + @current_user.name
= render 'posts/form'
= link_to 'Back to All Posts', posts_path
%br

app/views/posts/index.html.haml
%h1.page-header Today's Posts
= form_tag search_path,:method => :post do
  = label_tag 'Search Posts'
  = text_field_tag :query
  = select :category,:category_id, @categories.map {|c| [c.name,c.id]}
  = submit_tag 'Find'
- @posts.each do |post|
  %h3.modal-header= post.title
  %p= 'in ' + post.category.name
  %p.container-fluid= truncate(post.content)
  %p= 'by ' + post.printed_user_name
  - if (@current_user and post.user_id.eql? @current_user.id) or @current_admin
    = link_to 'Edit',edit_post_path(post)
    = link_to 'Delete',post_path(post),:method => :delete
  %p= 'Tagged with ' + post.tag_string
  = link_to 'Read',post_path(post)
  %br

app/views/posts/new.html.haml
%h3.page-header= 'New post by ' + @current_user.name
= render 'posts/form'

app/views/posts/show.html.haml
%h2.page-header= @post.title
%p= 'in ' + @post.category.name
%p= @post.content
%p= 'by ' + @post.printed_user_name
%p= 'Tagged with ' + @post.tag_string
%p= 'It has received ' + PostVote.where(:post_id => @post.id).count.to_s + ' vote'.pluralize(PostVote.where(:post_id => @post.id).count)
-if (@current_user and @post.user_id.eql? @current_user.id) or @current_admin
  = link_to 'Edit',edit_post_path(@post)
  = link_to 'Delete',post_path(@post),:method => :delete
-if (@current_user and not @post.user_id.eql? @current_user.id)
  -if @vote.nil?
    = render 'post_votes/form'
  -else
    = button_to '-',{:controller => :post_votes,:action => :destroy ,:id => @vote.id},:method => :delete
%br
%h3.page-header= 'Comments'
%br
= render 'comments/show'
- if @current_user
  = render 'comments/form'
= link_to 'Back to All Posts', posts_path
%br