config/routes.rb
Channelback::Application.routes.draw do

get '/users/sign_in' => 'users#sign_in',:as => :sign_in
get '/admin/sign_in' => 'admins#sign_in',:as => :admin_sign_in
get '/admin' => 'admins#sign_in'
get '/admin/users' => 'users#index',:as => :admin_users
get '/admin/activity' => 'admins#activity',:as => :activity
post '/users/sign_in' => 'users#login',:as => :login
post '/admin/sign_in' => 'admins#login',:as => :admin_login
post '/users/logout' => 'users#logout',:as => :logout
post '/admin/logout' => 'admins#logout',:as => :admin_logout
post '/comment_votes/:id' => 'comment_votes#destroy'
post '/posts/search' => 'posts#search',:as => :search
post '/admin/users/:id' => 'users#promote'
delete '/admin/users/:id' => 'users#demote'
root :to => 'posts#index'
resources :users
resources :posts
resources :admins
resources :categories
resources :comments
resources :post_votes
resources :comment_votes

end

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top
  .navbar.navbar-inverse
    .navbar-inner
      .container
        .brand= 'ChannelBack'
        %ul.nav
          - if is_admin_page?
            - if @current_admin
              = render 'admins/dashboard_links'
            - else
              %li.navbar-link= link_to 'Sign In', admin_sign_in_path
          -else
            - if @current_user
              = render 'users/user_links'
            - elsif @current_admin
              = render 'admins/dashboard_links'
            - else
              %li.navbar-link= link_to 'Sign In', sign_in_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Channelback</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


            <div class='container'>
              <% if flash[:error] -%>
                  <p class='alert alert-error'><%=h flash[:error] %></p>
              <% end -%>
              <% if flash[:notice] -%>
                  <p class='alert alert-info'><%=h flash[:notice] %></p>
              <% end -%>
              <%= render 'layouts/header' %>

              <%= yield %>
            </div>
</body>
</html>